import Head from 'next/head';

export default function Home() {
  return (
    <div className="container mx-auto h-screen bg-slate-50">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl font-bold underline">Eisenhower matrix</h1>
      <div className="h-3/4">
        <div className="flex h-1/2">
          <div className="w-1/2 h-auto flex justify-center items-center shadow-xl rounded-xl m-3">
            Card 1
          </div>
          <div className="w-1/2 h-auto flex justify-center items-center shadow-xl rounded-xl m-3">
            Card 2
          </div>
        </div>
        <div className="flex h-1/2">
          <div className="w-1/2 h-auto flex justify-center items-center shadow-xl rounded-xl m-3">
            Card 3
          </div>
          <div className="w-1/2 h-auto flex justify-center items-center shadow-xl rounded-xl m-3">
            Card 4
          </div>
        </div>
      </div>
    </div>
  );
}
